version: '3.4'
services:
    postgresql:
        image: postgres:latest
        container_name: postgresql
        environment:
            POSTGRES_DB: video
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
        ports:
            - 5432:5432
        volumes:
            - ./external-apps/db/:/docker-entrypoint-initdb.d
        hostname: postgres
        restart: always
        user: root
    ms-api:
        image: ms-api:latest
        container_name: ms-api
        ports:
            - 8080:8080
        extra_hosts:
            - localhost:host-gateway
        depends_on:
            - postgresql
        volumes:
            - ./external-apps/logs:/go/src/ms-api/logs
            - ./external-apps/assets:/go/src/ms-api/assets
        hostname: ms-api
        restart: always
        user: root
    ms-stream-api:
        image: ms-stream-api:latest
        container_name: ms-stream-api
        ports:
            - 8081:8081
        extra_hosts:
            - localhost:host-gateway
        volumes:
            - ./external-apps/logs:/go/src/ms-stream-api/logs
            - ./external-apps/assets:/go/src/ms-stream-api/assets
        hostname: ms-stream-api
        restart: always
        user: root
    ms-recommendation-api:
        image: ms-recommendation-api:latest
        container_name: ms-recommendation-api
        ports:
            - 8082:8082
        extra_hosts:
            - localhost:host-gateway
        volumes:
            - ./external-apps/logs:/app/logs
        depends_on:
            - postgresql
        hostname: ms-recommendation-api
        restart: always
        user: root
    ms-website:
        image: ms-website:latest
        container_name: ms-website
        ports:
            - 3000:3000
        extra_hosts:
            - localhost:host-gateway
        depends_on:
            - ms-api
            - ms-stream-api
            - ms-recommendation-api
        hostname: ms-website
        restart: always
        user: root
