apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ms-website-istio-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ms-tv.local"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms-website-istio
spec:
  hosts:
  - "ms-tv.local"
  gateways:
  - ms-website-istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: ms-website-gateway
